Rename & Refactor of DAG Elements
phylovi/bito pull request #382
Opened 2021-11-15 18:14 UTC by davidrich27

## Description

Please include a summary of the change.

Closes #350 
Closes #375 

## Tests

Please describe the tests added to verify correct behavior.
Please double check that you can make your tests fail by perturbing them.

## Checklist:

* [ ] Code follows our detailed [contribution guidelines](CONTRIBUTING.md)
* [ ] `clang-format` has been run
* [ ] TODOs have been eliminated from the code
* [ ] Comments are up to date, document intent, and there are no commented-out code blocks

2022-02-08 19:35 UTC, matsen requested changes

2022-02-08 19:35 UTC, matsen commented on src/bitset.cpp
> +bool Bitset::EdgeIsLeaf() const {
PCSPChildIsLeaf

2022-02-08 19:35 UTC, matsen commented on src/bitset.hpp
> +    LEFT = 0,  /* ROTATED, LEXICO_SMALLER, BIN_LARGER */
Clean comments

2022-02-08 19:35 UTC, matsen commented on src/bitset.hpp
> +  // A "leaf" (formerly "leaf") subsplit is a subsplit where one of the clades is equal
check

2022-02-08 19:35 UTC, matsen commented on src/bitset.hpp
> +  static Bitset RootSubsplitOfTaxonCount(const size_t taxon_count);
UCA, please

2022-02-08 19:35 UTC, matsen commented on src/bitset.cpp
> +  for (bool clade : {0, 1}) {
false, true

2022-02-08 19:35 UTC, matsen commented on src/bitset.cpp
> +Bitset Bitset::EdgeToLeaf(const Bitset& parent_subsplit) {
LeafSubsplit

2022-02-08 19:35 UTC, matsen commented on src/gp_doctest.cpp
> +  // (NOT_VALID) Nodes are not adjacent (12|34 and 2|4).
Please drop NOT_VALID and see if we can use CHECK_FALSE

2022-02-08 19:35 UTC, matsen commented on src/gp_engine.hpp
> +  // Make copy of engine, resize to contain
fix

2022-02-08 19:35 UTC, matsen commented on src/gp_engine.hpp
> +  //
fix

2022-02-08 19:35 UTC, matsen commented on src/gp_engine.hpp
> +  void FunctionOverRootedTreeCollection(
Already exists in main... double check

2022-02-08 19:35 UTC, matsen commented on src/subsplit_dag.hpp
> +  // Iterate over the rootward edges, supplying both the a PCSP index of the edge and
check

2022-02-08 19:35 UTC, matsen commented on src/subsplit_dag.hpp
> +  std::map<std::string, size_t> dag_taxons_;
"taxa" rather than "taxons"

2022-02-08 19:35 UTC, matsen commented on src/subsplit_dag.hpp
> +  //    - [ Taxon Name => Taxon Id (Bitset Clade Position) ]
(represented as the position of the "on" bit in the clade)

2022-02-08 19:35 UTC, matsen commented on src/subsplit_dag.hpp
> +  //    - [ (parent_id, child_id) Node Id Pairs => Edge/PCSP Idxs. ]
can drop PCSP here

2022-02-08 19:35 UTC, matsen commented on src/subsplit_dag.hpp
> +  // WARNING: Does not check for redundant nodes.
I prefer names that indicate unsafe behavior.

2022-02-08 19:35 UTC, matsen commented on src/subsplit_dag_node.hpp
> +    LEFTSIDE = 0, /* ROTATED */
Left / Right

2022-02-08 19:35 UTC, matsen commented on src/subsplit_dag_node.hpp
> +  SizeVector leafward_leftward_;
left_leafward_

2022-02-08 19:35 UTC, matsen commented on src/tidy_subsplit_dag.hpp
> + private:
why move?

2022-02-08 23:48 UTC, davidrich27 commented on src/tidy_subsplit_dag.hpp
> + private:
Removed redundant `private`

2022-02-09 00:32 UTC, matsen requested changes
@davidrich27 just a few things here... looking nice! Thank you!

2022-02-09 00:32 UTC, matsen commented on src/bitset.cpp
> +// ** Edge functions
```suggestion
// ** PCSP functions
```

2022-02-09 00:32 UTC, matsen commented on src/bitset.hpp
> +  // MultiClade). Subsplits are composed of two clades and Edges are composed of three
```suggestion
  // MultiClade). Subsplits are composed of two clades and PCSPs are composed of three
```

Maybe have a little search?

2022-02-09 00:32 UTC, matsen commented on src/bitset.hpp
> +  // to their lexicographic taxon ordering: the smaller "left" (or "sorted") clade
we can drop the old terminology

2022-02-09 00:32 UTC, matsen commented on src/gp_doctest.cpp
> +  // (NOT_VALID) Parent node does not have a parent (12|3 and 1|2).
remove NOT_VALID

2022-02-09 00:32 UTC, matsen commented on src/sbn_maps.cpp
> +  Bitset dag_root(Bitset::UCASubsplitOfTaxonCount(taxon_count));
let's flip this `dag_root` over to `dag_uca` and look for other instances.

2022-02-09 00:32 UTC, matsen commented on src/subsplit_dag_node.cpp
> +    return (GetRootwardRightward().size() + GetRootwardLeftward().size() == 0);
There's still a lot of leftward and rightward

2022-02-09 13:51 UTC, merged